### PR TITLE
Testing Class updated

### PR DESCRIPTION
**Pull request by shashankspole**
hi, 
i have sent updated code 

thank you

### CODE REVIEW

**Comment by ShashankPole** [comment]
hi X,
Good work, u just add one more check...

regards
S

**Comment by ShashankPole** [comment]
hi X,
please check code and send me again
regards 
S

**Comment by shashankspole** [comment]
hi S,
new code sent

**Comment by ShashankPole** [comment]
hi  X,
ok u merge the code

**Pull request merged**
